FROM node:20-alpine AS builder
WORKDIR /app
ARG VITE_API_URL="https://cyberpanel-soc-production.up.railway.app"
ENV VITE_API_URL=$VITE_API_URL
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/build ./build
ENV PORT=3000
EXPOSE $PORT
CMD ["sh", "-c", "serve -s build -l ${PORT:-3000}"]
